### ISSUE TITLE
Bustaim prints console errors (Weapon ID seems to be invalid)

### ISSUE THREAD

**Issue by sondrekje** [YashasSamaga/BustAim-AntiAimbot#3]
`[22:35:07] [debug] #0 0003aff4 in OnPlayerWeaponShot (playerid=0, weaponid=128, hittype=96, hitid=46295, Float:fX=1631428965014962200.00000, Float:fY=0.00000, Float:fZ=0.00000, ... <1073741816 arguments>) at C:\Users\sondr\git\lsrcr/pawno/include\bustaim.inc:251
[22:35:07] [debug] #1 0000aeb4 in public OnPlayerWeaponShot (... <7 arguments>) at C:\Users\sondr\git\lsrcr/pawno/include\YSI\YSI\..\YSI_Coding\..\YSI_Internal\y_cgen.inc:32
[22:35:07] [debug] Run time error 4: "Array index out of bounds"`

I am not entirely sure what it was caused by, but it could very well be because of a cheater. When it occured we had a cheater in-game, not sure what he was doing though, but he was autobanned a bit later for flying cheats. I have also noticed the errors before, hence why I am reporting them, don't think it's a really big issue though as they are very rare.

**Comment by YashasSamaga** [comment]
https://github.com/YashasSamaga/BustAim-AntiAimbot/blob/master/BustAim.inc#L249-L278

That code should've actually prevented it. Check if you are using an older version of the include.

**Comment by sondrekje** [comment]
I forgot about this, sorry for leaving the issue open. You were probably right as I have not seen the errors again.
